apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-15T16:32:13Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: paymahn-nginx-deployment
  namespace: paymahn
  resourceVersion: "192327666"
  selfLink: /apis/extensions/v1beta1/namespaces/paymahn/deployments/paymahn-nginx-deployment
  uid: a20947b1-96c9-11ea-a9cc-da8609e8d9ee
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/tags: '{"cnab.installation":"paymahn-nginx-staging-us.paymahn.general1.us1.ddbuild.io"}'
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
